name: MineDrop
main: net.alextwelshie.minedrop.Main
version: 1.3
authors: [HowlingAbyss, AlexTWelshie, MylesLovesMemes]
commands:
   bg:
      usage: /bg
   eg:
      usage: /eg
   setconfig:
      usage: /setconfig
