name: MineDrop
main: net.alextwelshie.minedrop.Main
version: 1.5
authors: [HowlingAbyss, AlexTWelshie, MylesLovesMemes]
commands:
  forcestart:
    description: Force start a game
    aliases: fs
  endgame:
    description: End the game instantly
    aliases: eg
  shortstart:
    description:
    aliases: ss
  map:
    description: Choose the map manually
  setconfig:
    description: Set configuration values.
    aliases: sc
  setspawn:
    description: set spawn points for map
